@Practice_and_homework2_HostAddress = http://localhost:5022

### GET ALL ITEMS
GET {{Practice_and_homework2_HostAddress}}/api/items
Accept: application/json

### GET ITEM BY ID
GET {{Practice_and_homework2_HostAddress}}/api/items/1
Accept: application/json

### SEACH BY NAME "MercedesPetronas"
GET {{Practice_and_homework2_HostAddress}}/api/Items/search?name=MercedesPetronas
Accept: application/json

### SEACH BY NAME "AstonMartin"
GET {{Practice_and_homework2_HostAddress}}/api/Items/search?name=AstonMartin
Accept: application/json

### SEACH BY NAME WITHOUT QUERY PARAMETRS
GET {{Practice_and_homework2_HostAddress}}/api/Items/search
Accept: application/json

### CREATE NEW ITEM
POST {{Practice_and_homework2_HostAddress}}/api/items?name=AstonMartin
Content-Type: application/json

### CREATE NEW ITEM WITHOUT NAME
POST {{Practice_and_homework2_HostAddress}}/api/items
Content-Type: application/json

### UPDATE ITEM ID 2 TO "OracaleRedBullRacing"
PUT {{Practice_and_homework2_HostAddress}}/api/items/2?name=OracaleRedBullRacing
Content-Type: application/json

### DELETE ITEM BY ID 3
DELETE {{Practice_and_homework2_HostAddress}}/api/items/3
Accept: application/json

### DELETE ITEM BY ID 10 (NOT EXIST)
DELETE {{Practice_and_homework2_HostAddress}}/api/items/10
Accept: application/json