@Practice_and_homework2_HostAddress = http://localhost:5022

### GET ALL ITEMS
GET {{Practice_and_homework2_HostAddress}}/api/items
Accept: application/json

### GET ITEM BY ID 
GET {{Practice_and_homework2_HostAddress}}/api/items/3
Accept: application/json

### GET ITEM BY NON-EXISTENT ID
GET {{Practice_and_homework2_HostAddress}}/api/items/999
Accept: application/json

### SEARCH ITEMS BY NAME
GET {{Practice_and_homework2_HostAddress}}/api/items/search?name=Mercedes
Accept: application/json

### SEARCH ITEMS BY NAME 
GET {{Practice_and_homework2_HostAddress}}/api/items/search?name=AstonMartin
Accept: application/json

### SEARCH ITEMS WITHOUT NAME PARAMETER
GET {{Practice_and_homework2_HostAddress}}/api/items/search
Accept: application/json

### CREATE NEW ITEM
POST {{Practice_and_homework2_HostAddress}}/api/items
Content-Type: application/json
Accept: application/json

{
  "name": "Aston Martin"
}

### CREATE ITEM WITHOUT NAME
POST {{Practice_and_homework2_HostAddress}}/api/items
Content-Type: application/json
Accept: application/json

{
}

### UPDATE ITEM ID 2 TO “Oracle Red Bull Racing”
PUT {{Practice_and_homework2_HostAddress}}/api/items/2
Content-Type: application/json
Accept: application/json

{
  "name": "Oracle Red Bull Racing"
}

### DELETE ITEM BY ID 3
DELETE {{Practice_and_homework2_HostAddress}}/api/items/3
Accept: application/json

### DELETE NON-EXISTENT ITEM BY ID 10
DELETE {{Practice_and_homework2_HostAddress}}/api/items/10
Accept: application/json